version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: app_bolao_postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "app_bolao"
    ports:
      - "5432:5432"
    volumes:
      ## For Windows users: it is highly recommended run docker on WSL2 otherwise
      ## YOU MIGHT HAVE PROBLEMS WITH THE BIND MOUNT (C:\desenvolvimento\Volumes\APP_BOLAO)
      - C:\desenvolvimento\Volumes\APP_BOLAO:/var/lib/postgresql/data